version: '3.8'

services:
  postgres:
    restart: always
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: quick-meet
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  core-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/quick-meet
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234


#  prometheus:
#    image: prom/prometheus
#    ports:
#      - "9090:9090"
#    volumes:
#      - ./config/prometheus-local.yml:/etc/prometheus/prometheus.yml
#
#  grafana:
#    image: grafana/grafana
#    ports:
#      - "3000:3000"
#    environment:
#      - GF_SECURITY_ADMIN_USER=admin
#      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  postgres-data: