version: '3.8'

services:
  postgres:
    restart: always
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: quick-meet
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "admin1234"
      MINIO_ACCESS_KEY: "admin"
      MINIO_SECRET_KEY: "admin1234"
    volumes:
      - ./data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address :9001

  rabbitmq:
    image: pcloud/rabbitmq-stomp
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER : admin
      RABBITMQ_DEFAULT_PASS : admin
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"
    volumes:
      - '~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/mnesia/'

  messenger-app:
    build: ./messenger-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - redis
      - minio
      - core-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/quick-meet-messenger
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_RABBITMQ_HOST : rabbitmq

  core-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - minio
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/quick-meet
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_REDIS_HOST : redis
      SPRING_REDIS_PORT : 6379
      SPRING_MINIO_URL : http://minio:9000
      SPRING_RABBITMQ_HOST : rabbitmq


#  prometheus:
#    image: prom/prometheus
#    ports:
#      - "9090:9090"
#    volumes:
#      - ./config/prometheus-local.yml:/etc/prometheus/prometheus.yml
#
#  grafana:
#    image: grafana/grafana
#    ports:
#      - "3000:3000"
#    environment:
#      - GF_SECURITY_ADMIN_USER=admin
#      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  postgres-data:
  minio:
  rabbitmq:
