# ssh -i Desktop/id_ed25519 quickm3et@158.160.18.176
# dev-properties
#@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
server:
  port: 8080
#${random.int(8080,8085)} For Spring cloud
spring:
  main:
    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        generate_statistics: true # only for development
  application:
    name : "quick-meet"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: "jdbc:postgresql://localhost:5432/quick-meet"
    username: "postgres"
    password: "1234"

  jackson:
    serialization:
      fail-on-empty-beans: false

  cache:
    type: redis

  redis:
    host: localhost
    port: 6379

  minio:
    url: http://localhost:9000
    access-key : admin
    secret-key : admin1234
    create-bucket: true
    bucket: "file-storage"

  rabbitmq:
    host: localhost
    username: admin
    password: admin

logging:
#  level:
#    org.springframework.data.*.* : trace
#    org.springframework.cache.* : trace
#    org.hibernate.stat : DEBUG # only for development
  pattern:
    console: "%d{HH:mm:ss} [%-5level] %C{1.} - %msg%n"


management:
  endpoints.web.exposure.include: '*'
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: false # true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": false # true

application:
  meet-status-job : true
  meet-job-limit : 100
  meet-validation :
    use-rule : true
    validate-cross-time : true
    required-rank : 2.0
    premium-account :
      meet-limit-per-day : 3
      meet-max-capacity : 30
      update-limit : 1
      meet-highlight : true
      icon-update : base
    base-account :
      meet-limit-per-day: 1
      meet-max-capacity: 10
      update-limit : 1
      meet-highlight : false
      icon-update : none
    vip-account:
      meet-limit-per-day: 5
      meet-max-capacity: 1000
      update-limit: 1
      meet-highlight : true
      icon-update : custom
    business-account:
      meet-limit-per-day: 10000
      meet-max-capacity: 10000
      update-limit: 1
      meet-highlight : true
      icon-update : custom
  verification:
    test-code : true
    phone : false
    mail : true


jwt:
  secret: test-secret
  token:
    refresh:
      expire: 30
    access:
      expire: 30


error:
  response:
    stacktrace: true

#--------------region logging------------------
#logging.file.name = logs/spring-boot-logging.log
#logging.pattern.file= %d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%
#logging.level.org.springframework.web=INFO
#logging.level.guru.springframework.controllers=DEBUG
#logging.level.org.hibernate=ERROR

