# ssh -i Desktop/id_ed25519 quickm3et@158.160.18.176
# dev-properties
server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    properties:
#      hibernate:
#        generate_statistics: true # only for development
  application:
    name : "quick-meet"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: "jdbc:postgresql://localhost:5432/quick-meet"
    username: "postgres"
    password: "1234"

  jackson:
    serialization:
      fail-on-empty-beans: false

  cache:
    type: redis
    redis:
      time-to-live: 15m

  redis:
    host: localhost
    port: 6379

logging:
#  level:
#    org.springframework.data.*.* : trace
#    org.springframework.cache.* : trace
#    org.hibernate.stat : DEBUG # only for development
  pattern:
    console: "%d{HH:mm:ss} [%-5level] %C{1.} - %msg%n"



management:
  endpoints.web.exposure.include: 'prometheus, health'
  metrics:
    export:
      prometheus:
        enabled: false # true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": false # true

application:
  meet-status-job : true
  meet-job-limit : 100
  meet-creation :
    use-rule : true
    validate-cross-time : true
    required-rank : 2.0
    gold-account :
      meet-limit-per-day : 10
      meet-max-capacity : 1000
    base-account :
      meet-limit-per-day: 2
      meet-max-capacity: 10


jwt:
  secret: test-secret
  token:
    refresh:
      expire: 30
    access:
      expire: 30


phone:
  confirmation:
    disable: true


error:
  response:
    stacktrace: true

#--------------region logging------------------
#logging.file.name = logs/spring-boot-logging.log
#logging.pattern.file= %d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%
#logging.level.org.springframework.web=INFO
#logging.level.guru.springframework.controllers=DEBUG
#logging.level.org.hibernate=ERROR

