# ssh -i Desktop/id_ed25519 quickm3et@158.160.18.176
# dev-properties
server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name : "quick-meet"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: "jdbc:postgresql://localhost:5432/quick-meet"
    username: "postgres"
    password: "1234"

  jackson:
    serialization:
      fail-on-empty-beans: false

logging:
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"

management:
  endpoints.web.exposure.include: 'prometheus, health'
  metrics:
    export:
      prometheus:
        enabled: false # true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": false # true


jwt:
  secret: test-secret
  token:
    refresh:
      expire: 30
    access:
      expire: 30


phone:
  confirmation:
    disable: true


error:
  response:
    stacktrace: true

#--------------region logging------------------
#logging.file.name = logs/spring-boot-logging.log
#logging.pattern.file= %d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%
#logging.level.org.springframework.web=INFO
#logging.level.guru.springframework.controllers=DEBUG
#logging.level.org.hibernate=ERROR

#--------------region server-------------------



#--------------region application--------------

#mail.confirmation = false

#client.endpoint = http://localhost:3000
#backend.endpoint = http://localhost:8081
#classpath:file-storage
#upload.path = /Users/danilbogatov/IdeaProjects/DigitalWind/backend/src/main/resources/file-storage
#upload.path = /Users/dmitry_yugai/IdeaProjects/DigitalWind/backend/src/main/resources/file-storage
#upload.path = /Users/danilbogatov/Desktop/file-storage
#upload.path = /app/file-storage

#admin.login=test
#admin.password=test

#--------------region email-------------------- Digital-password dvjanclgkjullagi digital-wind-noreply@yandex.ru
#spring.mail.host=smtp.yandex.ru
#spring.mail.username=digital-wind-noreply@yandex.ru
#spring.mail.password=dvjanclgkjullagi
#spring.mail.port=465
#spring.mail.protocol=smtps
#mail.debug=false
